
services:
  db:
    image: postgres:latest # Imagem do postgres mais recente
    restart: unless-stopped # Reiniciar o container a menos que seja parado
    ports:
      - ${DATABASE_PORT_WEBSOCKET}:5432 # Porta do postgres padrão
    environment:
      POSTGRES_USER: ${DATABASE_USER} # Usuário do postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD} # Senha do postgres
      POSTGRES_DB: ${DATABASE_NAME} # Nome do banco de dados

    volumes:
      - db:/var/lib/postgresql/data # Volume para armazenar os dados do postgres

  pgadmin:
    image: dpage/pgadmin4:latest 
    restart: unless-stopped 
    depends_on: # Dependência do pgadmin com o postgres
      - db
    ports:
      - ${PGADMIN_PORT}:80 # Porta do pgadmin padrão
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL} # Email do pgadmin
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD} # Senha do pgadmin
    volumes:
      - pgadmin:/var/lib/pgadmin # Volume para armazenar os dados do pgadmin

volumes:
  db:
    driver: local # Armazenamento local
  pgadmin:
    driver: local # Armazenamento local